---
- hosts: all
  become_method: sudo
  become: yes
  become_user: root
  vars:
    mount_point: "/mnt/nfsshare"
    mount_source: "192.168.188.32:/var/nfsshare"

  tasks:
    - name: insall nfs-utils
      yum:
        name: nfs-utils
        state: present

    - name: ensure nfs mount folder exists
      file:
        path: "{{ mount_point }}"
        state: directory

    - name: start the services
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - rpcbind
        - nfs-server
        - nfs-lock
        - nfs-idmap

    - name: mount folder
      mount:
        name: "{{ mount_point }}"
        src: "{{ mount_source }}"
        fstype: nfs
        state: present
